application: i-oo-i
version: 2
runtime: python
api_version: 1

default_expiration: '3650d'
skip_files: |
  ^(.*/)?(
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (cron\.yaml)|
  (cron\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.po)|
  (.*\.pot)|
  (\..*)|
  (app\.yaml\.sample)|
  (index\.yaml\.sample)|
  (cron\.yaml\.sample)|
  (manage\.py)|
  (TODO)|
  (TODO\.pdf)|
  (README)|
  (README\.pdf)|
  (LICENSE)|
  (docs\/.*)|
  (design\/.*)|
  (Ad\/.*)|
  (gaegene\/.*)|
  (kay\/tests\/.*)|
  )$

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /media/admin
  static_dir: django/contrib/admin/media/
  
- url: /media
  static_dir: media
  secure: optional
  
- url: /favicon\.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico

- url: /robots\.txt 
  static_files: media/robots.txt
  upload: media/robots.txt

- url: /gaebar/static
  static_dir: gaebar/static

- url: /.*
  script: djangoappengine/main/main.py
  
